apiVersion: v1
kind: Service
metadata:
  name: cloud-devops
spec:
  type: LoadBalancer
  selector:
    app: cloud-devops
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-devops-deploy
spec:
  selector:
    matchLabels:
      app: cloud-devops
  replicas: 2
  template:
    metadata:
      labels:
        app: cloud-devops
    spec:
      containers:
      - name: cloud-devops-pod
        image: pabloalbaladejo/cloud-devops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
  strategy:
    type: RollingUpdate